name: DocumentAI CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: pytest

    - name: Check code formatting
      run: black --check .

    - name: Linting
      run: flake8

    - name: Build Documentation
      run: |
        pip install -r docs/requirements.txt
        sphinx-build -b html docs/source docs/build

    - name: Publish to PyPI
      if: github.ref == 'refs/tags/v*'
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
