name: DocumentAI CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: pytest DocumentAI_std/tests

    - name: Check code formatting
      run: black --check .

#    - name: Publish to PyPI
#      if: github.ref == 'refs/tags/v*'
#      run: |
#        python setup.py sdist bdist_wheel
#        twine upload dist/*
